// Packs the optimised models in assets/models into js/models_data.js as base64, so the park can load them with a
// plain <script> tag — that works from file:// (the tests, opening index.html directly) as well as over http.
// Run after changing anything in assets/models: `npm run pack-models`.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets/models');
const files = readdirSync(dir).filter((f) => f.endsWith('.glb')).sort();
let out = '/* generated by scripts/pack-models.mjs from assets/models/*.glb — do not edit */\nWT.MODEL_DATA = {\n';
let total = 0;
for (const f of files) {
  const b = readFileSync(join(dir, f));
  total += b.length;
  out += `  ${JSON.stringify(f.replace(/\.glb$/, ''))}: '${b.toString('base64')}',\n`;
}
out += '};\n';
writeFileSync(join(root, 'js/models_data.js'), out);
console.log(`packed ${files.length} models (${(total / 1024) | 0} KB) into js/models_data.js`);
